### ISSUE TITLE
User-Can-See-Their-Car

### ISSUE THREAD

**Issue by adrienne-yung** [adrienneyung64/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

![toyboat image](https://user-images.githubusercontent.com/90871776/147794370-7f7ea41f-96ff-464d-b7ed-2025ed76e663.png)

## ✅ Task List

- [x] Choose a vehicle that you will be using for the project
- [x] Pick a background color for your landscape
- [x] Have your vehicle start off at the top left of your landscape
