### ISSUE TITLE
User-can-turn-their-car

### ISSUE THREAD

**Issue by adrienne-yung** [adrienneyung64/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a main.js file and link it with your index.html
- [ ] Apply 4 classes, one for each direction (North, South, East, West) to your index.html vehicle
- [ ] In your stylesheet, rotate your image according to its class name
- [ ] In your main.js file, create an addEventListener that listens to 'keydown' for each direction.
- [ ] Only apply the class when when keydown is associated to its corresponding direction
